[package]
name = "sine"
version = "0.1.0"
edition = "2021"
authors = ["Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license = "ISC"

[lib]
crate-type = ["cdylib"]

[features]
default = ["au"]
au = ["nih_plug/au"]

[dependencies]
nih_plug = { path = "../../../", features = ["assert_process_allocs"] }
